---
- name: Install NetBox IPAM
  hosts: netbox
  remote_user: root

  tasks:
    - name: Create Netbox user
      user:
        name: netbox
        system: yes
        state: present
    
    - name: Install the required packages for NetBox
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - python3-dev
        - build-essential
        - libxml2-dev
        - libxslt1-dev
        - libffi-dev
        - libpq-dev
        - libssl-dev
        - zlib1g-dev
        - postgresql
        - redis-server
    
    - name: Update Pip3 to latest version
      pip:
       name: pip
       state: latest

    - name: Install psycopg2
      pip:
        name: psycopg2-binary
        state: present
        
    - name: Create NetBox Databse
      postgresql_db:
        state: present
        name: netbox
      become: yes
      become_user: postgres

    - name: Create NetBox User in Database
      postgresql_user:
        state: present
        user: netbox
        password: "Insert Strong password Here"
      become: yes
      become_user: postgres

    - name: Grant Netbox User Access to Database
      postgresql_privs:
        type: database
        database: netbox
        roles: netbox
        grant_option: no
        privs: all
      become: yes
      become_user: postgres
    
    - name: Download and unarchive netbox   
      unarchive:
        src: https://github.com/netbox-community/netbox/archive/v3.0.10.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/netbox-3.0.10/base_requirements.txt

    - name: Create Symlink for NetBox
      file:
        src: /opt/netbox-3.0.10
        dest: /opt/netbox
        state: link

    - name: Copy example config
      copy: 
        src: /opt/netbox-3.0.10/netbox/netbox/configuration.example.py
        dest: /opt/netbox-3.0.10/netbox/netbox/configuration.py
